apiVersion: configuration.konghq.com/v1
kind: KongClusterPlugin
metadata:
  name: global-cors-dev
  annotations:
    kubernetes.io/ingress.class: tna-ohos
config:
  origins:
    - "*"
  credentials: true
  max_age: 3600
  preflight_continue: false
plugin: cors