apiVersion: apps/v1
kind: Deployment
metadata:
  name: ciim-tna
  namespace: etna
spec:
  template:
    spec:
      containers:
        - name: ciim
          image: public.ecr.aws/v3w7q3a1/tna-ciim:dev-7.4.14