es:
  version: 7x
  clusters:
    - code: internal
      label: Internal Admin
      description: The main search index containing all data in the internal data model
      active: true
      cluster: ciim-internal-etna
      node: ciim-internal-etna-client
      host: ciim-internal-etna-es-http.etna
      port: 9200
      pingTimeout: 10s
      protocol: http
      pathPrefix:
      username: elastic
      password: 323RWM9jU5XZ2Mkn190lre8B
      mediaBase: http://localhost/mediaLib
      indices:
        - ciim
        - management
        - unavailable
    - code: Public
      label: Rosetta
      description: The main search index containing all data in the internal data model
      active: true
      cluster: ciim-public
      node: ciim-public-client
      host: ciim-public-es-http.etna
      port: 9200
      pingTimeout: 10s
      protocol: http
      pathPrefix:
      username: elastic
      password: Kng6K7J41j882P77EQeS9cTI
      mediaBase: http://localhost/mediaLib
      indices:
        - ciim
dataSource:
  url: jdbc:mysql://ciim-db-service.etna/ciim_mgmt?zeroDateTimeBehavior=convertToNull&autoReconnect=true&characterEncoding=utf8&maxReconnects=10&initialTimeout=10&allowPublicKeyRetrieval=true&useSSL=false
  dialect: org.hibernate.dialect.MySQL8Dialect
  driverClassName: com.mysql.cj.jdbc.Driver
  username: ciim
  password: xxxx
  dbCreate: update
template:
  create:
    default: true
ws:
  allowedOrigin: "*"
  broadcastUrlForCore: ws://ciim-management:18080/ciim/stomp
  broadcastUrlForWeb: ws://afa13a7c0067b4f01991b0bad9e003a4-edf0e30af2b95f5f.elb.eu-west-2.amazonaws.com/ciim/stomp