rosetta:
  cache:
    enabled: false
  monitoring:
    log_stages: false

  provider:
    providers:
      - name: elasticsearch
        type: elasticsearch
        properties:
          host: ciim-public-es-http.etna
          port: 9200
          index: ciim
          username: elastic
          password: Kng6K7J41j882P77EQeS9cTI
          global_timeout_millis: 1000000
          timeout_millis: 100000

  profile:
    profiles:
      - name: iiif
        providers:
          policy: list
          names:
            - elasticsearch
        transforms:
          request:
            - glyphs:
                policy: list
                names:
                  - iiif-mapping

  transform:
    enabled: true
    timeout_millis: 30000
    glyphs:
      - name: iiif-mapping
        type: proteus
        properties:
          spec: ./config/request-transform.spec
          mutable: true
          include:
            - ./config/component_search.json
            - ./config/iiif-mapping.json


  plugins:
    iiif:
      profile: iiif
      base_url: https://rosetta-staging.k-int.com/
      external_media_base_url: https://rosetta-staging.k-int.com/image/iiif/3/
      iiif_media_base_url: https://rosetta-staging.k-int.com/image/iiif/3/
      mediaArtifact: mid
      identifier_type: iaid
