apiVersion: apps/v1
kind: Deployment
metadata:
  name: rosetta-3-export-ohos
  namespace: tna-ohos
spec:
  selector:
    matchLabels:
      app: rosetta-3-export-ohos
  revisionHistoryLimit: 1
  replicas: 1
  progressDeadlineSeconds: 600
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: rosetta-3-export-ohos
    spec:
      terminationGracePeriodSeconds: 60
      volumes:
        - name: rosetta-3-export-config
          configMap:
            name: rosetta-3-export-config
        - name: rosetta-export
          persistentVolumeClaim:
            claimName: rosetta-export-pvc
      initContainers:
        - name: set-rosetta-permissions
          image: registry.hub.docker.com/library/busybox:latest
          imagePullPolicy: IfNotPresent
          command: [ '/bin/sh' ]
          args:
            - -c
            - >-
              chmod -R 777 /rosetta/export
          volumeMounts:
            - name: rosetta-export
              mountPath: /rosetta/export
      imagePullSecrets:
        - name: regcred
      containers:
        - name: rosetta
          image: public.ecr.aws/v3w7q3a1/rosetta:tna-Export
          imagePullPolicy: Always
          ports:
            - name: rosetta-port
              containerPort: 4923
              protocol: TCP
          volumeMounts:
            - name: rosetta-3-export-config
              mountPath: /rosetta/config
            - name: rosetta-export
              mountPath: /rosetta/export
          env:
            - name: JAVA_OPTS
              value: "-Dspring.profiles.active=non-default-for-trace-logging -XX:MaxRAMPercentage=80.0 -XX:+PrintFlagsFinal -XX:+UseZGC"
          resources:
            requests:
              memory: 4Gi
---
apiVersion: v1
kind: Service
metadata:
  name: rosetta-3-export-service
  namespace: tna-ohos
spec:
  type: ClusterIP
  selector:
    app: rosetta-3-export-ohos
  ports:
    - protocol: TCP
      port: 4923
      targetPort: 4923
      name: rosetta-port
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rosetta-export-pvc
  namespace: tna-ohos
spec:
  storageClassName: ebs-sc-scalable
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi