base_paths:
  proteus: ./config

spring:
  graphql:
    path: /rosetta-3/graphql
    graphiql:
      enabled: true
      path: /rosetta-3/graphiql
    schema:
      locations: file:${base_paths.proteus}/

rosetta:
  graphql:
    max_depth: 15
    max_complexity: 64
  view:
    views:
      - name: search
        paths:
          - /search
        profile: default
        transforms:
          request:
            policy: list
            names:
              - to-generic-search
          response:
            policy: list
            names:
              - to-simple-data-response

  profile:
    profiles:
      - name: default
        providers:
          policy: list
          names:
            - elasticsearch
        transforms:
          request:
            - glyphs:
                policy: list
                names:
                  - elastic-generic-search

      - name: graphql
        providers:
          policy: list
          names:
            - elasticsearch
        transforms:
          request:
            - glyphs:
                policy: list
                names:
                  - unpack-request
                  - elastic-generic-search
                  - add-source
          data:
            - glyphs:
                policy: list
                names:
                  - data-modification

  provider:
    providers:
      - name: elasticsearch
        type: elasticsearch
        properties:
          host: ciim-public-tna-es-http.tna-ohos
          port: 9200
          index: ciim
          username: elastic
          password: g19415GWedJc1Zbv4w87pw5K
          client_timeout: 60000
          skip_ping: true

  transform:
    glyphs:
      - name: to-generic-search
        type: to-generic-search

      - name: to-simple-data-response
        type: to-simple-data-response

      - name: elastic-generic-search
        type: elastic-generic-search
        properties:
          default_aggregation_size: 30
          path_config:
            paths:
              colour: "colour.value.keyword"
              community_archive_ID: "community.summary.title.keyword"
              condition: "condition.value.keyword"
              latitude: "coordinates.lat"
              longitude: "coordinates.lon"
              copies: "copies.value.keyword"
              date: "creation.date.from"
              description: "description.value.keyword"
              location_named_entity: "enrichment.loc.value.keyword"
              date_named_entity: "enrichment.date.value"
              miscellaneous_named_entity: "enrichment.misc.value.keyword"
              organisation_named_entity: "enrichment.org.value.keyword"
              person_named_entity: "enrichment.per.value.keyword"
              item_hierarchy: "hierarchy.summary.title.keyword"
              identifier: "identifier.value.keyword"
              inscription: "inscription.value"
              owner: "institution.name.value.keyword"
              rights_holder: "legal.rights.holder"
              rights: "legal.rights.type"
              level: "level.value"
              licence: "licence.value.keyword"
              creator: "creation.maker.name.value.keyword"
              extent: "measurements.dimensions.value"
              format: "name.value.keyword"
              community_archive: "organisation.name.value.keyword"
              parent_record_ID: "parent.@admin.id"
              location: "place.name.value.keyword"
              location_hierarchy: "place.hierarchy.value.keyword"
              provenance: provenance.text.value.keyword
              publisher: creation.publisher.name.value.keyword
              place_of_deposit: "repository.code.value.keyword"
              subject: "subject.summary.title.keyword"
              title: "summary.title.keyword"
          date_aggregations:
            - path: "enrichment.date.from"
              agg_name: "enrichment_date"
              format: "y G || y"
              date_ranges: &date_ranges
                - from: "9000 BC"
                  to: "1 BC"
                - from: "1"
                  to: "0100"
                - from: "0101"
                  to: "0200"
                - from: "0201"
                  to: "0300"
                - from: "0301"
                  to: "0400"
                - from: "0401"
                  to: "0500"
                - from: "0501"
                  to: "0600"
                - from: "0601"
                  to: "0700"
                - from: "0701"
                  to: "0800"
                - from: "0801"
                  to: "0900"
                - from: "0901"
                  to: "1000"
                - from: "1001"
                  to: "1100"
                - from: "1101"
                  to: "1200"
                - from: "1201"
                  to: "1300"
                - from: "1301"
                  to: "1400"
                - from: "1401"
                  to: "1500"
                - from: "1501"
                  to: "1600"
                - from: "1601"
                  to: "1700"
                - from: "1701"
                  to: "1800"
                - from: "1801"
                  to: "1900"
                - from: "1901"
                  to: "2000"
                - from: "2001"
                  to: "2100"
            - path: "creation.date.from"
              agg_name: "creation_date"
              format: "y G || y"
              date_ranges:
                *date_ranges

      - name: data-modification
        type: proteus
        properties:
          mutable: true
          spec: ${base_paths.proteus}/data-modification.json

      - name: add-source
        type: proteus
        input: full
        properties:
          mutable: true
          spec: ${base_paths.proteus}/add-source.json
          config:
            properties:
              fields:
                colour: "colour.value"
                community_archive_ID: "community.*"
                condition: "condition.value"
                latitude: "coordinates.lat"
                longitude: "coordinates.lon"
                copies: "copies.value"
                date: "creation.date.*"
                description: "description.value"
                date_named_entity: "enrichment.date.*"
                location_named_entity: "enrichment.loc.*"
                miscellaneous_named_entity: "enrichment.misc.*"
                organisation_named_entity: "enrichment.org.*"
                person_named_entity: "enrichment.per.*"
                item_hierarchy: "hierarchy.@admin.id"
                admin_ID : "@admin.id"
                community_identifier: "identifier.*"
                inscription: "inscription.value"
                owner: "institution.*"
                rights_holder: "legal.rights.holder"
                rights: "legal.rights.type"
                level: "level.value"
                licence: "licence.value"
                creator: "creation.maker.*"
                extent: "measurements.dimensions"
                format: "name.*"
                community_archive: "organisation.*"
                parent_record_ID: "parent.*"
                location: "place.name.value"
                location_hierarchy: "place.hierarchy.value"
                provenance: provenance.text.value
                publisher: creation.publisher.name.value
                place_of_deposit: "repository.code.value"
                subject: "subject.summary.title"
                title: "summary.title"

      - name: unpack-request
        type: proteus
        input: full
        properties:
          mutable: true
          spec: ${base_paths.proteus}/unpack-request.json


