apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-rosetta-3
  namespace: etna
  annotations:
    konghq.com/plugins: request-transform-etna
spec:
  ingressClassName:  etna
  rules:
    - http:
        paths:
          - path: /rosetta-3
            pathType: Prefix
            backend:
              service:
                name: rosetta-3-service-test
                port:
                  name: rosetta-port