global:
  ciim:
    appName: staging-etna

deployment:
  replicas: 1
  image:
    repository: public.ecr.aws/v3w7q3a1/tna-ciim:staging-0.1
  env:
    - name: processors.iadata.batchUpdate.s3.accessKey
      valueFrom:
        secretKeyRef:
          name: aws-key
          key: aws-key
    - name: processors.iadata.batchUpdate.s3.secretAccessKey
      valueFrom:
        secretKeyRef:
          name: aws-secret
          key: aws-secret
  envFrom:
    - secretRef:
        name: mongodb-staging-url
    - secretRef:
        name: wagtail-es-password

encryptionKey:
  existingSecret:
    name: ciim-encryption-key
    key: ciim.encryption_key

config:
  persisted:
    object:
      processors.iadata.batchUpdate.s3.bucket: ds-live-ciim-update
      processors.iadata.batchUpdate.s3.region: eu-west-2
      wagtail.es.hostname: es.master-7rqtwti-tvehemlvvjb4k.uk-1.platformsh.site
      wagtail.es.scheme: https
      wagtail.es.port: 443
      wagtail.es.user: elastic
      media.replica.main.s3.bucket_name: ds-live-digital-files
      flags.manual_add_processed_media_artifacts: false
      flags.remove_ambiguous_dates: true
      flags.mock_doris_client: false
      flags.add_prefabricated_taxonomies: false
  transient:
    object:
      processing.default.validator: com.k_int.ciim.core.tna.Validator
      processing.default.stream: tna|tna|TNA Default Stream|com.k_int.ciim.core.tna.Validator
      processing.default.idgenerator: com.k_int.ciim.commons.id.BasicIdGenerator

      media.process.files: false
      media.gmagick.version: 1
      media.zoom.processing.enabled: false

externalDatabase:
  host: ciim-db-service.etna
  schemas:
    main: etna-staging
    vault: etna-staging-vault
    archive: etna-staging-archive
  urlParams: autoReconnect=true&allowPublicKeyRetrieval=true&useSSL=false
  existingSecret:
    name: db-secret
    key: password

database:
  enabled: false

keycloak:
  enabled: false

management:
  enabled: false

ingress:
  enabled: false

kong:
  enabled: false

