global:
  ciim:
    appName: staging-etna

deployment:
  replicas: 1
  image:
    repository: public.ecr.aws/v3w7q3a1/tna-ciim:staging-0.1

encryptionKey:
  existingSecret:
    name: ciim-encryption-key
    key: ciim.encryption_key

config:
  persisted:
    object:
      flags.manual_add_processed_media_artifacts: false
      flags.remove_ambiguous_dates: true
      flags.mock_doris_client: false
      flags.add_prefabricated_taxonomies: false
  transient:
    object:
      processing.default.validator: com.k_int.ciim.core.tna.Validator
      processing.default.stream: tna|tna|TNA Default Stream|com.k_int.ciim.core.tna.Validator
      processing.default.idgenerator: com.k_int.ciim.commons.id.BasicIdGenerator

      media.process.files: true
      media.zoom.processing.enabled: false

externalDatabase:
  host: ciim-db-service.etna
  schemas:
    main: etna-staging
    vault: etna-staging-vault
    archive: etna-staging-archive
  urlParams: autoReconnect=true&allowPublicKeyRetrieval=true&useSSL=false
  existingSecret:
    name: db-secret
    key: password

database:
  enabled: false

keycloak:
  enabled: false

management:
  enabled: false

ingress:
  enabled: false

kong:
  enabled: false

