base_paths:
  data: /rosetta/config

rosetta:
  cache:
    enabled: false
  request:
    max_size: 10000000

  monitoring:
    log_stages: false
  
  profile:
    profiles:
      - name: default
        providers:
          policy: all
        profiles:
          policy: all
        glyphs:
          policy: list
          names:
            - api-default

  transform:
    enabled: true
    timeout_millis: 2000000
    glyphs:
      - name: api-default
        type: proteus
        properties:
          mutable: true
          spec: ./config/jpt.json

  provider:
    providers:
      - name: elasticsearch
        type: elasticsearch
        properties:
          host: ciim-public-tna-es-http.tna-ohos
          port: 9200
          index: ciim
          username: elastic
          password: JlPX89V2VflMp61ID78859Zw
          date_aggregations:
            - path: "creation.date.from"
              agg_name: "fromDate"
            - path: "creation.date.to"
              agg_name: "toDate"
          path_config:
            paths:
              datatype: "@datatype.base"
              property: "property.name.value.keyword"
              place: "place.name.value.keyword"
              collection: "parent.summary.title.keyword"
              date: "creation.date.from"
              title: "summary.title.keyword"
              group: "@datatype.group.value"
    global_timeout_millis: 2000000
    timeout_millis: 2000000

logging:
  level:
    com.k_int.rosetta.ext: trace
    com.k_int.rosetta.profile: trace
    com.k_int.rosetta.transform: trace
    com.k_int.rosetta.core: trace