namespace: etna
resources:
  - rosetta.yml
  - ingress.yml
  - es_ingress.yml
  - cantaloupe_ingress.yml
  - cantaloupe_ciim_ingress.yml
  - ingress_ciim.yml
  - rewriteplugin.yml
configMapGenerator:
  - name: rosetta-config
    files:
      - ./config/application.yml
      - ./config/jpt.json
      - ./config/component_search.json