namespace: etna
resources:
  - rosetta.yml
  - ingress.yml
  - es_ingress.yml
  - es-service.yml
configMapGenerator:
  - name: rosetta-config
    files:
      - ./config/application.yml
      - ./config/jpt.json