es:
  version: 7x
  clusters:
    - code: internal
      label: Internal Admin
      description: The main search index containing all data in the internal data model
      active: true
      cluster: ciim-internal-dev
      node: ciim-internal-tna-client
      host: ciim-internal-tna-es-http.tna-ohos
      port: 9200
      pingTimeout: 10s
      protocol: http
      pathPrefix:
      username: elastic
      password: u1e6w21mh2L3F571QL0LTuHa
      mediaBase: http://http://a08001c6c1d2e4c58bdf02589da33fca-0f850b505f873e8e.elb.eu-west-2.amazonaws.com/tna/api/secure/ui/media/
      indices:
        - ciim
        - management
        - unavailable
dataSource:
  url: jdbc:mysql://ciim-db-service.etna/ciim_mgmt_ohos?zeroDateTimeBehavior=convertToNull&autoReconnect=true&characterEncoding=utf8&maxReconnects=10&initialTimeout=10&allowPublicKeyRetrieval=true&useSSL=false
  dialect: org.hibernate.dialect.MySQL8Dialect
  driverClassName: com.mysql.cj.jdbc.Driver
  username: admin
  password: jTh339%w=3$
  dbCreate: update
template:
  create:
    default: true
ws:
  allowedOrigin: "*"
  broadcastUrlForCore: ws://ui-service.tna-ohos:18080/ciim/stomp
  broadcastUrlForWeb: ws://a08001c6c1d2e4c58bdf02589da33fca-0f850b505f873e8e.elb.eu-west-2.amazonaws.com/ciim/stomp