apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: ciim-public
  namespace: etna
spec:
  nodeSets:
    - count: 1
      name: default
      podTemplate:
        spec:
          containers:
            - env:
                - name: ES_JAVA_OPTS
                  value: '-Xms24g -Xmx24g -Dlog4j2.formatMsgNoLookups=true'
              name: elasticsearch
              resources:
                requests:
                  memory: 24Gi
              volumeMounts:
                - mountPath: /usr/share/elasticsearch/config/dictionaries
                  name: esdictionaries
          initContainers:
            - command:
                - sh
                - '-c'
                - sysctl -w vm.max_map_count=262144
              name: sysctl
              securityContext:
                privileged: true
          volumes:
            - configMap:
                name: esdictionaries
              name: esdictionaries
      volumeClaimTemplates:
        - metadata:
            name: elasticsearch-data
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 500Gi