base_paths:
  proteus: ./config

rosetta:
  admin:
    enabled: true

  plugins:
    advanced_cache:
      enabled: true
      caches:
        - name: fast-cache
          expire_after_write: 5m
          maximum_size: 100
          use_scheduler: true

        - name: slow-cache
          expire_after_write: 1h
          maximum_size: 100
          use_scheduler: true

        - name: eds-auth-cache
  cache:
    enabled: true
    manager:
      enabled: false

  view:
    views:
      - name: ciim/search
        paths:
          - /rosetta/data/search
        profile: elasticsearch
        type: advanced-cache-multi
        transforms:
          request:
            policy: list
            names:
              - to-generic-search
              - generic-search-defaults
              - generic-search-modifications
              - generic-to-elastic
              - elastic-modifications
              - ciim/search/request
          response:
            policy: list
            names:
              - ciim/search/response
              - aggs-count-to-doc-count

      - name: ciim/get
        paths:
          - /rosetta/data/get
        profile: generic-search
        transforms:
          request:
            policy: list
            names:
              - ciim/get/request
          response:
            policy: list
            names:
              - ciim/get/response

  profile:
    profiles:
      - name: elasticsearch
        providers:
          policy: list
          names:
            - elasticsearch
            - elasticsearchEtna
        transforms:
          data: &global-data-transforms
            - glyphs:
                policy: list
                names:
                  - singularize-creation
      - name: generic-search
        providers:
          policy: list
          names:
            - elasticsearch
            - elasticsearchEtna
        transforms:
          request:
            - glyphs:
                policy: list
                names:
                  - generic-to-elastic
          data: *global-data-transforms

  transform:
    timeout_millis: 60000
    glyphs:
      # Elastic search glyphs
      - name: to-generic-search
        type: to-generic-search
        properties:
          types:
            - query

      - name: generic-search-defaults
        type: proteus-simple
        properties:
          mutable: true
          spec: ${base_paths.proteus}/generic_search_defaults.json

      - name: generic-search-modifications
        type: proteus
        input: full
        properties:
          mutable: true
          spec: ${base_paths.proteus}/generic_search_modifications.json

      - name: generic-to-elastic
        type: elastic-generic-search
        properties:
          index: public-es
          request_timeout: 60000
          date_aggregations:
            - path: "creation.date.from"
              agg_name: "fromDate"
            - path: "creation.date.to"
              agg_name: "toDate"
            - path: "origination.date.from"
              agg_name: "coveringFromDate"
            - path: "origination.date.to"
              agg_name: "coveringToDate"
            - path: "enrichment.date.from"
              agg_name: "enrichmentDate"
              format: "yyyy"
              date_ranges:
                - from: "0100"
                  to: "1500"
                - from: "1501"
                  to: "1600"
                - from: "1601"
                  to: "1700"
                - from: "1701"
                  to: "1800"
                - from: "1801"
                  to: "1850"
                - from: "1851"
                  to: "1900"
                - from: "1951"
                  to: "2000"
                - from: "2001"
                  to: "2050"
            - path: "creation.date.from"
              agg_name: "dateCentury"
              format: "yyyy"
              date_ranges:
                - from: "-9000"
                  to: "-8901"
                - from: "-8900"
                  to: "-8801"
                - from: "-8800"
                  to: "-8701"
                - from: "-8700"
                  to: "-8601"
                - from: "-8600"
                  to: "-8501"
                - from: "-8500"
                  to: "-8401"
                - from: "-8400"
                  to: "-8301"
                - from: "-8300"
                  to: "-8201"
                - from: "-8200"
                  to: "-8101"
                - from: "-8100"
                  to: "-8001"
                - from: "-8000"
                  to: "-7901"
                - from: "-7900"
                  to: "-7801"
                - from: "-7800"
                  to: "-7701"
                - from: "-7700"
                  to: "-7601"
                - from: "-7600"
                  to: "-7501"
                - from: "-7500"
                  to: "-7401"
                - from: "-7400"
                  to: "-7301"
                - from: "-7300"
                  to: "-7201"
                - from: "-7200"
                  to: "-7101"
                - from: "-7100"
                  to: "-7001"
                - from: "-7000"
                  to: "-6901"
                - from: "-6900"
                  to: "-6801"
                - from: "-6800"
                  to: "-6701"
                - from: "-6700"
                  to: "-6601"
                - from: "-6600"
                  to: "-6501"
                - from: "-6500"
                  to: "-6401"
                - from: "-6400"
                  to: "-6301"
                - from: "-6300"
                  to: "-6201"
                - from: "-6200"
                  to: "-6101"
                - from: "-6100"
                  to: "-6001"
                - from: "-6000"
                  to: "-5901"
                - from: "-5900"
                  to: "-5801"
                - from: "-5800"
                  to: "-5701"
                - from: "-5700"
                  to: "-5601"
                - from: "-5600"
                  to: "-5501"
                - from: "-5500"
                  to: "-5401"
                - from: "-5400"
                  to: "-5301"
                - from: "-5300"
                  to: "-5201"
                - from: "-5200"
                  to: "-5101"
                - from: "-5100"
                  to: "-5001"
                - from: "-5000"
                  to: "-4901"
                - from: "-4900"
                  to: "-4801"
                - from: "-4800"
                  to: "-4701"
                - from: "-4700"
                  to: "-4601"
                - from: "-4600"
                  to: "-4501"
                - from: "-4500"
                  to: "-4401"
                - from: "-4400"
                  to: "-4301"
                - from: "-4300"
                  to: "-4201"
                - from: "-4200"
                  to: "-4101"
                - from: "-4100"
                  to: "-4001"
                - from: "-4000"
                  to: "-3901"
                - from: "-3900"
                  to: "-3801"
                - from: "-3800"
                  to: "-3701"
                - from: "-3700"
                  to: "-3601"
                - from: "-3600"
                  to: "-3501"
                - from: "-3500"
                  to: "-3401"
                - from: "-3400"
                  to: "-3301"
                - from: "-3300"
                  to: "-3201"
                - from: "-3200"
                  to: "-3101"
                - from: "-3100"
                  to: "-3001"
                - from: "-3000"
                  to: "-2901"
                - from: "-2900"
                  to: "-2801"
                - from: "-2800"
                  to: "-2701"
                - from: "-2700"
                  to: "-2601"
                - from: "-2600"
                  to: "-2501"
                - from: "-2500"
                  to: "-2401"
                - from: "-2400"
                  to: "-2301"
                - from: "-2300"
                  to: "-2201"
                - from: "-2200"
                  to: "-2101"
                - from: "-2100"
                  to: "-2001"
                - from: "-2000"
                  to: "-1901"
                - from: "-1900"
                  to: "-1801"
                - from: "-1800"
                  to: "-1701"
                - from: "-1700"
                  to: "-1601"
                - from: "-1600"
                  to: "-1501"
                - from: "-1500"
                  to: "-1401"
                - from: "-1400"
                  to: "-1301"
                - from: "-1300"
                  to: "-1201"
                - from: "-1200"
                  to: "-1101"
                - from: "-1100"
                  to: "-1001"
                - from: "-1000"
                  to: "-901"
                - from: "-900"
                  to: "-801"
                - from: "-800"
                  to: "-701"
                - from: "-700"
                  to: "-601"
                - from: "-600"
                  to: "-501"
                - from: "-500"
                  to: "-401"
                - from: "-400"
                  to: "-301"
                - from: "-300"
                  to: "-201"
                - from: "-200"
                  to: "-101"
                - from: "-100"
                  to: "0"
                - from: "1"
                  to: "100"
                - from: "101"
                  to: "200"
                - from: "201"
                  to: "300"
                - from: "301"
                  to: "400"
                - from: "401"
                  to: "500"
                - from: "501"
                  to: "600"
                - from: "601"
                  to: "700"
                - from: "701"
                  to: "800"
                - from: "801"
                  to: "900"
                - from: "901"
                  to: "1000"
                - from: "1001"
                  to: "1100"
                - from: "1101"
                  to: "1200"
                - from: "1201"
                  to: "1300"
                - from: "1301"
                  to: "1400"
                - from: "1401"
                  to: "1500"
                - from: "1501"
                  to: "1600"
                - from: "1601"
                  to: "1700"
                - from: "1701"
                  to: "1800"
                - from: "1801"
                  to: "1900"
                - from: "1901"
                  to: "2000"
                - from: "2001"
                  to: "2100"

          path_config:
            paths:
              datatype: "@datatype.base"
              property: "property.name.value.keyword"
              place: "place.name.value.keyword"
              collection: "parent.summary.title.keyword"
              date: "creation.date.from"
              title: "summary.title.keyword"
              group: "@datatype.group.value"
              community: "community.summary.title.keyword"
              collectionMorrab: "collectionMorrab.summary.title.keyword"
              collectionSurrey: "collectionSurrey.summary.title.keyword"
              enrichmentLoc: "enrichment.loc.value.keyword"
              enrichmentOrg: "enrichment.org.value.keyword"
              enrichmentPer: "enrichment.per.value.keyword"
              enrichmentMisc: "enrichment.misc.value.keyword"
          aggregation_configs:
            - name: group
              size: 50
            - name: collectionMorrab
              size: 50
            - name: collectionSurrey
              size: 50
            - name: enrichmentLoc
              size: 20
            - name: enrichmentLoc
              size: 20
            - name: enrichmentOrg
              size: 20
            - name: enrichmentPer
              size: 20
            - name: enrichmentMisc
              size: 20
            - name: enrichmentDate
              size: 20

      - name: ciim/search/request
        type: proteus
        properties:
          mutable: true
          spec: ${base_paths.proteus}/ciim_search_request.json

      - name: ciim/search/response
        type: proteus
        properties:
          mutable: true
          spec: ${base_paths.proteus}/ciim_search_response.json

      - name: ciim/get/request
        type: proteus
        properties:
          mutable: true
          spec: ${base_paths.proteus}/ciim_get_request.json

      - name: ciim/get/response
        type: proteus
        properties:
          mutable: true
          spec: ${base_paths.proteus}/ciim_get_response.json

      # Global data transforms
      - name: singularize-creation
        type: proteus
        properties:
          spec: ${base_paths.proteus}/singularize_creation.json
          config:
            accumulator: first

      # System glyphs
      - name: to-simple-data-response
        type: to-simple-data-response

      - name: aggs-count-to-doc-count
        type: proteus
        properties:
          mutable: true
          spec: ${base_paths.proteus}/aggs_count_to_doc_count.json

  provider:
    global_timeout: 500s
    timeout: 500s
    providers:
      - name: elasticsearch
        type: elasticsearch
        properties:
          host: ciim-public-tna-es-http.tna-ohos
          port: 9200
          index: ciim
          username: elastic
          password: g19415GWedJc1Zbv4w87pw5K
          client_timeout: 60000
          skip_ping: true
      - name: elasticsearchEtna
        type: elasticsearch
        properties:
          host: ciim-public-es-http.etna
          port: 9200
          index: ciim
          username: elastic
          password: Kng6K7J41j882P77EQeS9cTI

  monitoring:
    log_stages: true
