apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tna-ohos-ingress
  namespace: tna-ohos
  annotations:
    konghq.com/plugins: request-transform-ohos, global-cors-dev
spec:
  ingressClassName: tna-ohos
  tls:
    - hosts:
        - tna.rosetta.k-int.com
      secretName: tls-secret
  rules:
    - host: tna.rosetta.k-int.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: rosetta-3-service
                port:
                  name: rosetta-port
    - host: a08001c6c1d2e4c58bdf02589da33fca-0f850b505f873e8e.elb.eu-west-2.amazonaws.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: rosetta-3-service
                port:
                  name: rosetta-port
          - path: /tna/api/
            pathType: Prefix
            backend:
              service:
                name: ciim-service-tna
                port:
                  name: api-port
          - path: /ciim/
            pathType: Prefix
            backend:
              service:
                name: ui-service
                port:
                  name: ui-port
          - path: /ciim
            pathType: Prefix
            backend:
              service:
                name: ui-service
                port:
                  name: ui-port
          - path: /rosetta-3/export
            pathType: Prefix
            backend:
              service:
                name: rosetta-3-export-service
                port:
                  name: rosetta-port
          - path: /rosetta-3/graphql
            pathType: Prefix
            backend:
              service:
                name: rosetta-3-graphql-service
                port:
                  name: rosetta-port
          - path: /rosetta-3/graphiql
            pathType: Prefix
            backend:
              service:
                name: rosetta-3-graphql-service
                port:
                  name: rosetta-port