apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ohos-ingress-rosetta-3
  namespace: tna-ohos
  annotations:
    konghq.com/plugins: request-transform-ohos
spec:
  ingressClassName:  tna-ohos
  rules:
    - host: rosetta-ohos.nationalarchives.gov.uk
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: rosetta-3-service
                port:
                  name: rosetta-port