tenant:
  mode: static
  static: tna

access_tiers:
  viewer:
    prefix: /viewer/iiif/3/
    public_base_url: https://rosetta-staging.k-int.com/gateway/viewer/iiif/3
    max_width: 2000
    max_height: 2000
    redirect_ttl: 5m
  download:
    prefix: /download/iiif/3/
    public_base_url: https://rosetta-staging.k-int.com/gateway/download/iiif/3
    redirect_ttl: 10m

manifests:
  prefix: /iiif/3/manifest/
  redirect_ttl: 5m
  source:
    base_url: http://test-iiif-rosetta:4923/iiif/3/manifest/  #TODO update when iiif rosetta deployed

identifier_resolver:
  type: filepath

buckets:
  jpg: ds-staging-ptif-images
  ptif: ds-staging-ptif-images
  cache: ds-staging-iiif-cache
  cache_forbidden_is_miss: true #TODO, app doesn't have listObject permission atm so misses return as 403
  ptif_forbidden_is_miss: true #TODO, app doesn't have any permissions to ptif bucket atm

image_server:
  lambda:
    function_name: iiif-image-server

ptif_source:
  mode: convert
  converter:
    function_name: ptif-generator

memory_caches:
  identifiers:
    size: 10000
    ttl: 5m
  ptifs:
    size: 100000
    ttl: 5m