apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: iiif-gateway-monitor
  namespace: etna
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      app: iiif-gateway
  namespaceSelector:
    matchNames:
      - etna
  endpoints:
    - port: gateway-metrics
      path: /metrics
      interval: 15s