apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-acme
  namespace: tna-ohos
  annotations:
    konghq.com/protocols: "http"
spec:
  ingressClassName: tna-ohos
  rules:
    - http:
        paths:
          - path: /.well-known/acme-challenge
            pathType: Prefix
            backend:
              service:
                name: acme-service
                port:
                  number: 80