apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui-tna
  namespace: etna
spec:
  selector:
    matchLabels:
      app: ui-tna
  revisionHistoryLimit: 5
  replicas: 1
  progressDeadlineSeconds: 600
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: ui-tna
    spec:
      terminationGracePeriodSeconds: 60
      volumes:
        - name: ui-config
          configMap:
            name: ui-config
      containers:
        - name: ui
          image: public.ecr.aws/v3w7q3a1/ciim-management:7.0.7
          imagePullPolicy: Always
          ports:
            - name: ui-port
              containerPort: 18080
              protocol: TCP
          volumeMounts:
            - name: ui-config
              mountPath: /app/config
          env:
            - name: external.services.core.url
              value: http://ciim-service.etna:8080/tna/api
          resources:
            requests:
              memory: 4Gi
---
apiVersion: v1
kind: Service
metadata:
  name: ui-service
  namespace: etna
spec:
  type: ClusterIP
  selector:
    app: ui-tna
  ports:
    - protocol: TCP
      port: 18080
      targetPort: 18080
      name: ui-port