es:
  version: 7x
  clusters:
    - code: internal
      label: Internal Admin
      description: The main search index containing all data in the internal data model
      active: true
      cluster: ciim-internal
      node: ciim-internal-client
      host: ciim-internal-es-http.etna
      port: 9200
      pingTimeout: 10s
      protocol: http
      pathPrefix:
      username: elastic
      password: 5CVDe01b52t9fy5I83pvgFk5
      mediaBase: http://localhost/mediaLib
      indices:
        - ciim
        - management
        - unavailable
dataSource:
  url: jdbc:mysql://ciim-db-service.etna/ciim_mgmt_dev?zeroDateTimeBehavior=convertToNull&autoReconnect=true&characterEncoding=utf8&maxReconnects=10&initialTimeout=10&allowPublicKeyRetrieval=true&useSSL=false
  dialect: org.hibernate.dialect.MySQL8Dialect
  driverClassName: com.mysql.cj.jdbc.Driver
  username: ciim
  password: xxxx
  dbCreate: update
template:
  create:
    default: true
ws:
  allowedOrigin: "*"
  broadcastUrlForCore: ws://ciim-management:18080/ciim/stomp
  broadcastUrlForWeb: ws://aba8bbc248c7248429b60b3fcbfde942-e6a006db0770fe4b.elb.eu-west-2.amazonaws.com/ciim/stomp