fullnameOverride: chartmuseum
env:
  open:
    STORAGE: amazon
    STORAGE_AMAZON_BUCKET: ciim-helm-repo
    STORAGE_AMAZON_REGION: eu-west-1
    STORAGE_AMAZON_PREFIX:
  existingSecret: chartmuseum-secret
  existingSecretMappings:
    AWS_ACCESS_KEY_ID: aws-access-key
    AWS_SECRET_ACCESS_KEY: aws-secret-access-key